import {test,expect} from '@playwright/test';
import {rm} from 'node:fs/promises';
import {resolve} from 'node:path';

test('internal builder authors a draft and previews it with the regional engine',async({page,isMobile},testInfo)=>{
  test.setTimeout(90000);
  const slug=('ci-builder-ui-'+testInfo.project.name).toLowerCase().replace(/[^a-z0-9]+/g,'-');
  const cloneSlug=(slug+'-clone').slice(0,80);
  const pageErrors=[];
  page.on('pageerror',error=>pageErrors.push(error.message));
  const root=resolve(process.cwd(),'..');
  const draftBase=resolve(root,'data/platform/drafts',slug);
  const cloneDraftBase=resolve(root,'data/platform/drafts',cloneSlug);
  try{
    await page.goto('/__builder/',{waitUntil:'domcontentloaded'});
    const builderState=await page.request.get('/__builder/api/state').then(response=>response.json());
    const regionalJourneyCount=(builderState.catalog?.trips||[]).filter(item=>item.renderer==='regional-globe').length;
    await expect(page.locator('#heading')).toHaveText('Select or create a trip');
    if(isMobile)await page.locator('#mobileCoverageBtn').click();else await page.locator('#coverageBtn').click();
    await expect(page.locator('#coverageDialog')).toBeVisible();
    const coverageBounds=await page.locator('#coverageDialog').evaluate(el=>{const r=el.getBoundingClientRect();return{top:r.top,bottom:r.bottom,left:r.left,right:r.right,width:innerWidth,height:innerHeight}});
    expect(coverageBounds.top).toBeGreaterThanOrEqual(0);
    expect(coverageBounds.left).toBeGreaterThanOrEqual(0);
    expect(coverageBounds.bottom).toBeLessThanOrEqual(coverageBounds.height);
    expect(coverageBounds.right).toBeLessThanOrEqual(coverageBounds.width);
    await expect(page.locator('#coverageSummary')).toContainText('Coverage');
    await expect(page.locator('#coverageSummary')).toContainText('Profiles');
    const queueItems=page.locator('#coverageQueue .coverage-item');
    if(await queueItems.count())await expect(queueItems.first()).toBeVisible();
    else await expect(page.locator('#coverageQueue .coverage-empty')).toContainText('All published regional places have reusable experience content.');
    await expect(page.locator('#coverageJourneys .coverage-journey')).toHaveCount(regionalJourneyCount);
    await page.locator('#coverageDialog').screenshot({path:testInfo.outputPath('experience-coverage-'+testInfo.project.name+'.png'),animations:'disabled'});
    await page.locator('#coverageDialog [data-close="coverageDialog"]').click();
    await expect(page.locator('#coverageDialog')).not.toBeVisible();
    if(isMobile)await page.locator('#mobileLocaleCoverageBtn').click();else await page.locator('#localeCoverageBtn').click();
    await expect(page.locator('#localeCoverageDialog')).toBeVisible();
    await expect(page.locator('#localeCoverageSummary')).toContainText('Journeys');
    await expect(page.locator('#localeCoverageSummary')).toContainText('Locales');
    await expect(page.locator('#localeCoverageJourneys .coverage-journey').first()).toBeVisible();
    await page.locator('#localeCoverageDialog [data-close="localeCoverageDialog"]').click();
    await expect(page.locator('#localeCoverageDialog')).not.toBeVisible();
    if(isMobile)await page.locator('#mobileMaintenanceBtn').click();else await page.locator('#maintenanceBtn').click();
    await expect(page.locator('#maintenanceDialog')).toBeVisible();
    await expect(page.locator('#maintenanceSummary')).toContainText('External sources');
    await expect(page.locator('#maintenanceSummary')).toContainText('Reused sources');
    await expect(page.locator('#maintenanceQueue .maintenance-item').first()).toBeVisible();
    await expect(page.locator('#journeyHealth .maintenance-item').first()).toBeVisible();
    await page.locator('#maintenanceDialog').screenshot({path:testInfo.outputPath('maintenance-queue-'+testInfo.project.name+'.png'),animations:'disabled'});
    await page.locator('#maintenanceDialog [data-close="maintenanceDialog"]').click();
    await expect(page.locator('#maintenanceDialog')).not.toBeVisible();

    if(isMobile)await page.locator('#mobileCloneBtn').click();else await page.locator('#cloneBtn').click();
    await expect(page.locator('#cloneDialog')).toBeVisible();
    await page.locator('#cloneForm input[name="targetSlug"]').fill(cloneSlug);
    await page.locator('#cloneForm button[value="new"]').click();
    await expect(page.locator('#cloneDialog')).not.toBeVisible();
    await expect(page.locator('#slug')).toHaveValue(cloneSlug);
    await expect(page.locator('#status')).toHaveValue('draft');

    if(isMobile)await page.locator('#mobileNewBtn').click();else await page.locator('#newBtn').click();
    await expect(page.locator('#newDialog')).toBeVisible();
    await expect(page.locator('#newKind option')).toHaveCount(builderState.archetypes.length);
    await expect(page.locator('#newKind')).toContainText('rail');
    await page.locator('#newDialog [data-close="newDialog"]').click();

    await page.request.post('/__builder/api/scaffold',{data:{slug,kind:'island-hopping',days:8}});
    await page.reload({waitUntil:'domcontentloaded'});
    if(isMobile){await page.locator('#mobileDraftSelect').selectOption(slug)}else{await page.locator('[data-slug="'+slug+'"]').click()}
    await expect(page.locator('#editor')).toBeVisible();
    await expect(page.locator('[data-tab="localization"]')).toBeVisible();
    await expect(page.locator('[data-tab="trip"]')).toBeVisible();
    await expect(page.locator('[data-tab="catalog"]')).toBeVisible();
    await expect(page.locator('#skeletonBtn')).toBeVisible();
    await expect(page.locator('#evidenceBtn')).toBeVisible();
    await expect(page.locator('#localizationBtn')).toBeVisible();
    await page.locator('#localizationBtn').click();
    await expect(page.locator('#localizationDialog')).toBeVisible();
    await expect(page.locator('#localizationGrid .localization-card')).toHaveCount(6);
    await expect(page.locator('#localizationProgress')).toContainText('locales complete');
    await page.locator('#localizationDialog [data-close="localizationDialog"]').click();
    await expect(page.locator('#localizationDialog')).not.toBeVisible();
    await page.locator('#evidenceBtn').click();
    await expect(page.locator('#evidenceDialog')).toBeVisible();
    await expect(page.locator('#evidenceStatus')).toHaveValue('draft');
    await expect.poll(()=>page.locator('#evidenceLibrary option').count()).toBeGreaterThan(1);
    await page.locator('#evidenceLibrary').selectOption({index:1});
    await expect(page.locator('#evidenceForm input[name="url"]')).toHaveValue(/^https:\/\//);
    const evidenceBounds=await page.locator('#evidenceDialog').evaluate(el=>{const r=el.getBoundingClientRect();return{top:r.top,bottom:r.bottom,left:r.left,right:r.right,width:innerWidth,height:innerHeight}});
    expect(evidenceBounds.top).toBeGreaterThanOrEqual(0);
    expect(evidenceBounds.left).toBeGreaterThanOrEqual(0);
    expect(evidenceBounds.bottom).toBeLessThanOrEqual(evidenceBounds.height);
    expect(evidenceBounds.right).toBeLessThanOrEqual(evidenceBounds.width);
    await page.locator('#evidenceDialog [data-close="evidenceDialog"]').click();
    await expect(page.locator('#evidenceDialog')).not.toBeVisible();
    await page.locator('[data-tab="localization"]').click();
    await expect(page.locator('#jsonEditor')).toHaveValue(/"subtitle"/);
    await page.screenshot({path:testInfo.outputPath('trip-builder-'+testInfo.project.name+'.png'),fullPage:true,animations:'disabled'});

    const popupPromise=page.waitForEvent('popup');
    await page.locator('#previewBtn').click();
    const preview=await popupPromise;
    await expect(preview.locator('body')).toHaveClass(/platform-regional-trip/,{timeout:30000});
    await expect(preview.locator('#platformRouteBtn')).toBeVisible();
    await preview.close();
    expect(pageErrors,'trip builder runtime page errors').toEqual([]);
  }finally{
    await rm(draftBase+'.trip.json',{force:true});
    await rm(draftBase+'.catalog.json',{force:true});
    await rm(cloneDraftBase+'.trip.json',{force:true});
    await rm(cloneDraftBase+'.catalog.json',{force:true});
  }
});